### ISSUE TITLE
CShade Censor not working like it used to.

### ISSUE THREAD

**Issue by mrjoshisattvablack** [papadanku/CShade#16]
Hello my friend. I recently updated my reshade and addons.

I used to use CShade Censor to slightly pixellate my games to give a bit of a retro console psx / ps2 feel (which looked absolutely amazing on games like risk of rain 2 might I add). But I can no longer do this with the latest iteration. I'm not even sure how to explain the changes exactly as I'm not well versed in this kind of thing. But what I can say is that the previous iteration allowed for a more sensitive customisation of the pixellation if you know what I mean. Now even at "1" it is way too blocky and interferes with my ability to see important things in game. Is there any chance that in future iterations you can allow for a more sensitive customisation of the blockiness feature? if I remember correctly, the old iteration allowed you to have the pixellation at around half of what it currently is on "1", if you could bring that back, that would be amazing. I've attached a pic just for visual reference. As you can see in the top right, the mimimap text is unreadable. In the last iteration, or at least the iteration I used for the bulk of last year, I could customise the blockiness depending on the game to below what it is currently on "1" and avoid unreadable text or whatever else.

I've tried downloading and using the older iteration on the newest reshade but it doesn't seem to work. Maybe I'm doing something wrong, idk.

Either way, thanks in advance, even if this feature won't return, I had a lot of fun pretending I was playing modern games on psx last year so thank you for the experience!

![hCJTSfUTQi](https://github.com/user-attachments/assets/fe85df92-069f-41cd-a593-841b2321a9a2)

**Comment by papadanku** [comment]
Good morning,

First, thank you for trying out CShade and giving feedback. It helps!

I went through the code and found the issue: the default shader configuration. In your configuration, the shader pixelates regions that are **Less Than 1.000** (which is the whole screen).

I have made a couple of changes to the shader. First, you can now fine-tweak the Blockiness settings. Second, the default `Search Operator` now uses the old default.

Let me know if the new changes fix things. I recommend comparing it with default values!

Wish you a fun weekend!

**Comment by mrjoshisattvablack** [comment]
Good afternoon my friend!

Firstly, I love you. Secondly, thank you so much for resolving this issue so quickly. Really put a spring in my step today as I saw your reply just as I woke up and checked my email! I am going to have a brilliant weekend checking out how this looks on lots of different games now. Thank you so much.

Here's a screenshot for comparison. The difference is only subtle. And doesn't show up as much on a screenshot as it does actively. I can send you my reshade preset if you like so you can test for yourself? I've tweaked mine over the course of a year to improve upon colour and depth, it adds a slight crt overlay that is barely noticable, but noticable where it counts, and slight motion blur to emulate the blur most psx / ps2 games had to make animations seem more natural. I think you might enjoy it.

![UNAo6MSIgH](https://github.com/user-attachments/assets/2000d8fd-4bbf-4a50-bd3d-ce8d5b9fba26)

**Comment by papadanku** [comment]
Good morning,

Thank you for the kind comments! Feel free to send the preset here. Just attach it as a file. I need to try Path of Exile one day :D

**Comment by papadanku** [comment]
Feel free to comment, I shall close this issue for now
