### ISSUE TITLE
What happened to cShard.fx?

### ISSUE THREAD

**Issue by lapsio** [papadanku/CShade#17]
After last ReShade update I noticed that cShard.fx no longer compiles properly. Upon further investigation I realized that it's no longer present in this repository. So my question is - what happened to cShard (and few other) shader? Are they deprecated by some other shaders?

**Comment by papadanku** [comment]
cShard was deprecated by cCAS and cRCAS, as they are much more robust while using the same sample amount!

cRaySchism replaced cAutoExposure and cBloom

**Comment by ani917** [comment]
I have the same question about cFrameblend

**Comment by ani917** [comment]
@papadanku, are there any problems with cFrameblend porting to the new version? I couldn't find an alternative
add. after some searching I found a similar one called softmotion.fx, but if this filter is updated, it will be also good

**Comment by papadanku** [comment]
> [@papadanku](https://github.com/papadanku), are there any problems with cFrameblend porting to the new version? I couldn't find an alternative add. after some searching I found a similar one called softmotion.fx, but if this filter is updated, it will be also good

@ani917 Hi! cFrameBlend code is now in https://github.com/papadanku/CShade/blob/main/shaders/cGhost.fx
