### ISSUE TITLE
Folder structure issue

### ISSUE THREAD

**Issue by liuxd17thu** [papadanku/CShade#2]
Since all shaders have been packed into `cshade` folder now, when downloading CShade effects through ReShade official installer, the effect files are placed under `reshade-shaders/Shaders/CShade/cshade`. It is okay for ReShade to load them with recursive searching, but I think this is kind of weird.

**Comment by papadanku** [comment]
Fixed in https://github.com/papadanku/CShade/commit/4fdadb39ad3ad79663915f896d57389f4badc958
