### ISSUE TITLE
cOpticalFlow.fx instant ctd

### ISSUE THREAD

**Issue by WardedPredator** [papadanku/CShade#3]
Using latest version of reshade, start game or emulator bring up reshade UI and as soon as you click to enable cOpticalFlow.fx i get a instant crash to desktop with nothing in the log.

**Comment by papadanku** [comment]
Hmm, which API are you using?

**Comment by WardedPredator** [comment]
Tested using vulkan currently.

**Comment by papadanku** [comment]
Hi,

Can you test the current build amd see if it still crashes on Vulkan? Recently rewrote my stuff

Ty
