### ISSUE TITLE
cDLAA.fx: error X3120

### ISSUE THREAD

**Issue by simonedibilio** [papadanku/CShade#4]
**Describe the bug**
cDLAA.fx compilation throws exception X3120.

**To Reproduce**
1. Install ReShade with the CShade effect selected
2. Start the application
3. Let ReShade compile the installed effects

**Screenshots**
![image](https://github.com/user-attachments/assets/a8a9cba1-3aa6-46f8-abe0-3a0503f77989)

**Information (please complete the following information):**
 - Game: S.T.A.L.K.E.R. Anomaly
 - API: DX11 (AVX)
 - ReShade Version: 6.2.0

**Additional context**
Fresh installation, haven't touched anything in ReShade yet.

**Comment by papadanku** [comment]
Couple of things:

1. Thank your for trying out my shaders
2. It should be fixed now, update and see

**Comment by papadanku** [comment]
Should work now. Thank you!
